@echo off
setlocal EnableExtensions
title INSTALADOR IMPRESION LOCAL - GATO CALAVERA V5
color 0A
echo ================================================
echo  INSTALADOR IMPRESION LOCAL - GATO CALAVERA V5
echo ================================================
echo.
net session >nul 2>&1
if not %errorlevel%==0 (
  echo Solicitando permisos de administrador...
  powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Start-Process -FilePath '%~f0' -Verb RunAs"
  exit /b 0
)
set BASE=C:\GatoCalavera
set SVC=C:\GatoCalavera\print-service
set LOG=C:\GatoCalavera\logs
mkdir "%SVC%" >nul 2>&1
mkdir "%LOG%" >nul 2>&1
echo [1/6] Deteniendo tarea/proceso anterior si existe...
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "try { Unregister-ScheduledTask -TaskName 'GatoCalaveraPrintService' -Confirm:$false -ErrorAction SilentlyContinue } catch {}; try { Get-CimInstance Win32_Process ^| Where-Object { $_.CommandLine -like '*GatoCalavera*print-service*service.ps1*' } ^| ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue } } catch {}" >nul 2>&1
echo [2/6] Creando servicio local...
del "%SVC%\service.b64" >nul 2>&1
(
echo CiRFcnJvckFjdGlvblByZWZlcmVuY2UgPSAiQ29udGludWUiCiRQcmludGVyTmFtZSA9ICJU
echo RVJNSUNBIgokUG9ydCA9IDUwNTUKJEJhc2VEaXIgPSAiQzpcR2F0b0NhbGF2ZXJhIgokTG9n
echo RGlyID0gSm9pbi1QYXRoICRCYXNlRGlyICJsb2dzIgpOZXctSXRlbSAtSXRlbVR5cGUgRGly
echo ZWN0b3J5IC1Gb3JjZSAtUGF0aCAkTG9nRGlyIHwgT3V0LU51bGwKJExvZ0ZpbGUgPSBKb2lu
echo LVBhdGggJExvZ0RpciAicHJpbnQtc2VydmljZS5sb2ciCgpmdW5jdGlvbiBXcml0ZS1Mb2co
echo JG1zZykgewogICR0cyA9IEdldC1EYXRlIC1Gb3JtYXQgInl5eXktTU0tZGQgSEg6bW06c3Mi
echo CiAgQWRkLUNvbnRlbnQgLVBhdGggJExvZ0ZpbGUgLVZhbHVlICJbJHRzXSAkbXNnIiAtRW5j
echo b2RpbmcgVVRGOAp9CgpmdW5jdGlvbiBDbGVhbi1UZXh0KCR0ZXh0bykgewogIGlmICgkbnVs
echo bCAtZXEgJHRleHRvKSB7IHJldHVybiAiIiB9CiAgJHMgPSBbc3RyaW5nXSR0ZXh0bwogICRz
echo ID0gJHMuTm9ybWFsaXplKFtUZXh0Lk5vcm1hbGl6YXRpb25Gb3JtXTo6Rm9ybUQpCiAgJHNi
echo ID0gTmV3LU9iamVjdCBUZXh0LlN0cmluZ0J1aWxkZXIKICBmb3JlYWNoICgkY2ggaW4gJHMu
echo VG9DaGFyQXJyYXkoKSkgewogICAgJGNhdCA9IFtHbG9iYWxpemF0aW9uLkNoYXJVbmljb2Rl
echo SW5mb106OkdldFVuaWNvZGVDYXRlZ29yeSgkY2gpCiAgICBpZiAoJGNhdCAtbmUgW0dsb2Jh
echo bGl6YXRpb24uVW5pY29kZUNhdGVnb3J5XTo6Tm9uU3BhY2luZ01hcmspIHsgW3ZvaWRdJHNi
echo LkFwcGVuZCgkY2gpIH0KICB9CiAgJHMgPSAkc2IuVG9TdHJpbmcoKQogICRzID0gJHMgLXJl
echo cGxhY2UgIuKCoSIsICJDUkMgIgogICRzID0gJHMgLXJlcGxhY2UgIlteXHgwOVx4MEFceDBE
echo XHgyMC1ceDdFXSIsICIiCiAgcmV0dXJuICRzCn0KCmZ1bmN0aW9uIExpbmVhKCkgeyByZXR1
echo cm4gKCItIiAqIDQyKSArICJgbiIgfQpmdW5jdGlvbiBDZW50cm8oJHR4dCkgewogICR0ID0g
echo Q2xlYW4tVGV4dCAkdHh0CiAgaWYgKCR0Lkxlbmd0aCAtZ3QgNDIpIHsgJHQgPSAkdC5TdWJz
echo dHJpbmcoMCw0MikgfQogICRuID0gW01hdGhdOjpNYXgoMCwgW01hdGhdOjpGbG9vcigoNDIg
echo LSAkdC5MZW5ndGgpIC8gMikpCiAgcmV0dXJuICgiICIgKiAkbikgKyAkdCArICJgbiIKfQpm
echo dW5jdGlvbiBDb2woJGEsICRiKSB7CiAgJGwgPSBDbGVhbi1UZXh0ICRhCiAgJHIgPSBDbGVh
echo bi1UZXh0ICRiCiAgaWYgKCRsLkxlbmd0aCAtZ3QgMjQpIHsgJGwgPSAkbC5TdWJzdHJpbmco
echo MCwyNCkgfQogIGlmICgkci5MZW5ndGggLWd0IDE3KSB7ICRyID0gJHIuU3Vic3RyaW5nKDAs
echo MTcpIH0KICAkc3BhY2VzID0gNDIgLSAkbC5MZW5ndGggLSAkci5MZW5ndGgKICBpZiAoJHNw
echo YWNlcyAtbHQgMSkgeyAkc3BhY2VzID0gMSB9CiAgcmV0dXJuICRsICsgKCIgIiAqICRzcGFj
echo ZXMpICsgJHIgKyAiYG4iCn0KZnVuY3Rpb24gTW9uZXkoJG4pIHsKICB0cnkgeyByZXR1cm4g
echo IkNSQyAiICsgKFtkZWNpbWFsXSRuKS5Ub1N0cmluZygiTjAiLCBbR2xvYmFsaXphdGlvbi5D
echo dWx0dXJlSW5mb106OkdldEN1bHR1cmVJbmZvKCJlcy1DUiIpKSB9CiAgY2F0Y2ggeyByZXR1
echo cm4gIkNSQyAwIiB9Cn0KZnVuY3Rpb24gRmVjaGEoKSB7IHJldHVybiAoR2V0LURhdGUpLlRv
echo U3RyaW5nKCJkZC9NTS95eXl5IGhoOm1tIHR0IiwgW0dsb2JhbGl6YXRpb24uQ3VsdHVyZUlu
echo Zm9dOjpHZXRDdWx0dXJlSW5mbygiZXMtQ1IiKSkgfQoKZnVuY3Rpb24gUHJpbnQtVGV4dCgk
echo dGV4dG8pIHsKICAkcHJpbnRlciA9IEdldC1QcmludGVyIC1OYW1lICRQcmludGVyTmFtZSAt
echo RXJyb3JBY3Rpb24gU3RvcAogICR0bXAgPSBKb2luLVBhdGggJGVudjpURU1QICgiZ2F0by10
echo aWNrZXQtIiArIFtHdWlkXTo6TmV3R3VpZCgpLlRvU3RyaW5nKCkgKyAiLnR4dCIpCiAgJGNv
echo bnRlbnQgPSBDbGVhbi1UZXh0ICR0ZXh0bwogIFNldC1Db250ZW50IC1QYXRoICR0bXAgLVZh
echo bHVlICRjb250ZW50IC1FbmNvZGluZyBBU0NJSQogIEdldC1Db250ZW50IC1SYXcgJHRtcCB8
echo IE91dC1QcmludGVyIC1OYW1lICRQcmludGVyTmFtZQogIFJlbW92ZS1JdGVtICR0bXAgLUZv
echo cmNlIC1FcnJvckFjdGlvbiBTaWxlbnRseUNvbnRpbnVlCiAgV3JpdGUtTG9nICJUaWNrZXQg
echo ZW52aWFkbyBhICRQcmludGVyTmFtZSIKfQoKZnVuY3Rpb24gR2V0LUpzb25Cb2R5KCRjdHgp
echo IHsKICAkcmVhZGVyID0gTmV3LU9iamVjdCBJTy5TdHJlYW1SZWFkZXIoJGN0eC5SZXF1ZXN0
echo LklucHV0U3RyZWFtLCAkY3R4LlJlcXVlc3QuQ29udGVudEVuY29kaW5nKQogICRyYXcgPSAk
echo cmVhZGVyLlJlYWRUb0VuZCgpCiAgaWYgKFtzdHJpbmddOjpJc051bGxPcldoaXRlU3BhY2Uo
echo JHJhdykpIHsgcmV0dXJuIEB7fSB9CiAgdHJ5IHsgcmV0dXJuICRyYXcgfCBDb252ZXJ0RnJv
echo bS1Kc29uIH0KICBjYXRjaCB7IFdyaXRlLUxvZyAiSlNPTiBpbnZhbGlkbzogJHJhdyI7IHRo
echo cm93ICJKU09OIGludmFsaWRvIiB9Cn0KCmZ1bmN0aW9uIFNlbmQtSnNvbigkY3R4LCAkc3Rh
echo dHVzLCAkb2JqKSB7CiAgJGN0eC5SZXNwb25zZS5TdGF0dXNDb2RlID0gJHN0YXR1cwogICRj
echo dHguUmVzcG9uc2UuSGVhZGVycy5BZGQoIkFjY2Vzcy1Db250cm9sLUFsbG93LU9yaWdpbiIs
echo ICIqIikKICAkY3R4LlJlc3BvbnNlLkhlYWRlcnMuQWRkKCJBY2Nlc3MtQ29udHJvbC1BbGxv
echo dy1NZXRob2RzIiwgIkdFVCwgUE9TVCwgT1BUSU9OUyIpCiAgJGN0eC5SZXNwb25zZS5IZWFk
echo ZXJzLkFkZCgiQWNjZXNzLUNvbnRyb2wtQWxsb3ctSGVhZGVycyIsICJDb250ZW50LVR5cGUi
echo KQogICRjdHguUmVzcG9uc2UuQ29udGVudFR5cGUgPSAiYXBwbGljYXRpb24vanNvbjsgY2hh
echo cnNldD11dGYtOCIKICAkanNvbiA9ICRvYmogfCBDb252ZXJ0VG8tSnNvbiAtRGVwdGggMjAK
echo ICAkYnl0ZXMgPSBbVGV4dC5FbmNvZGluZ106OlVURjguR2V0Qnl0ZXMoJGpzb24pCiAgJGN0
echo eC5SZXNwb25zZS5PdXRwdXRTdHJlYW0uV3JpdGUoJGJ5dGVzLCAwLCAkYnl0ZXMuTGVuZ3Ro
echo KQogICRjdHguUmVzcG9uc2UuQ2xvc2UoKQp9CgpmdW5jdGlvbiBCdWlsZC1UZXN0VGlja2V0
echo KCkgewogICR0ID0gImBuIgogICR0ICs9IENlbnRybyAiR0FUTyBDQUxBVkVSQSIKICAkdCAr
echo PSBDZW50cm8gIlBSVUVCQSBERSBJTVBSRVNJT04iCiAgJHQgKz0gTGluZWEKICAkdCArPSBD
echo b2wgIkltcHJlc29yYSIgJFByaW50ZXJOYW1lCiAgJHQgKz0gQ29sICJFc3RhZG8iICJPSyIK
echo ICAkdCArPSBDb2wgIkZlY2hhIiAoRmVjaGEpCiAgJHQgKz0gTGluZWEKICAkdCArPSBDZW50
echo cm8gIlNFUlZJQ0lPIExPQ0FMIE9LIgogICR0ICs9ICJgbmBuYG4iCiAgcmV0dXJuICR0Cn0K
echo CmZ1bmN0aW9uIEdldC1Qcm9kdWN0b3MoJGRhdGEpIHsKICBpZiAoJG51bGwgLWVxICRkYXRh
echo LnByb2R1Y3RvcykgeyByZXR1cm4gQCgpIH0KICBpZiAoJGRhdGEucHJvZHVjdG9zIC1pcyBb
echo U3lzdGVtLkFycmF5XSkgeyByZXR1cm4gJGRhdGEucHJvZHVjdG9zIH0KICByZXR1cm4gQCgk
echo ZGF0YS5wcm9kdWN0b3MpCn0KCmZ1bmN0aW9uIEJ1aWxkLUZhY3R1cmEoJGRhdGEpIHsKICAk
echo cHJvZHVjdG9zID0gR2V0LVByb2R1Y3RvcyAkZGF0YQogICR0ID0gImBuIgogICR0ICs9IENl
echo bnRybyAiR0FUTyBDQUxBVkVSQSIKICAkdCArPSBDZW50cm8gIkZBQ1RVUkEiCiAgJHQgKz0g
echo TGluZWEKICAkdCArPSBDb2wgIk1lc2EiICgkZGF0YS5tZXNhIHwgRm9yRWFjaC1PYmplY3Qg
echo eyBpZigkXyl7JF99ZWxzZXsiTi9BIn0gfSkKICAkdCArPSBDb2wgIkZlY2hhIiAoRmVjaGEp
echo CiAgJHQgKz0gTGluZWEKICBmb3JlYWNoICgkcCBpbiAkcHJvZHVjdG9zKSB7CiAgICAkbm9t
echo YnJlID0gQ2xlYW4tVGV4dCAkcC5ub21icmUKICAgIGlmIChbc3RyaW5nXTo6SXNOdWxsT3JX
echo aGl0ZVNwYWNlKCRub21icmUpKSB7ICRub21icmUgPSAiUHJvZHVjdG8iIH0KICAgIGlmICgk
echo bm9tYnJlLkxlbmd0aCAtZ3QgMzIpIHsgJG5vbWJyZSA9ICRub21icmUuU3Vic3RyaW5nKDAs
echo MzIpIH0KICAgICRjYW50ID0gMQogICAgdHJ5IHsgJGNhbnQgPSBbZGVjaW1hbF0kcC5jYW50
echo aWRhZCB9IGNhdGNoIHt9CiAgICAkcHJlY2lvID0gMAogICAgdHJ5IHsgJHByZWNpbyA9IFtk
echo ZWNpbWFsXSRwLnByZWNpbyB9IGNhdGNoIHt9CiAgICAkc3VidG90YWwgPSAkY2FudCAqICRw
echo cmVjaW8KICAgICR0ICs9ICgiezB9IHggezF9YG4iIC1mICRjYW50LCAkbm9tYnJlKQogICAg
echo JHQgKz0gQ29sICIgIFByZWNpbyIgKE1vbmV5ICRwcmVjaW8pCiAgICAkdCArPSBDb2wgIiAg
echo U3VidG90YWwiIChNb25leSAkc3VidG90YWwpCiAgICAkdCArPSAiYG4iCiAgfQogICR0ICs9
echo IExpbmVhCiAgJHQgKz0gQ29sICJUT1RBTCIgKE1vbmV5ICRkYXRhLnRvdGFsKQogIGlmICgk
echo bnVsbCAtbmUgJGRhdGEuZWZlY3Rpdm8pIHsgJHQgKz0gQ29sICJFZmVjdGl2byIgKE1vbmV5
echo ICRkYXRhLmVmZWN0aXZvKSB9CiAgaWYgKCRudWxsIC1uZSAkZGF0YS52dWVsdG8pIHsgJHQg
echo Kz0gQ29sICJWdWVsdG8iIChNb25leSAkZGF0YS52dWVsdG8pIH0KICAkdCArPSBMaW5lYQog
echo ICR0ICs9IENlbnRybyAiR3JhY2lhcyBwb3Igc3UgY29tcHJhIgogICR0ICs9ICJgbmBuYG4i
echo CiAgcmV0dXJuICR0Cn0KCmZ1bmN0aW9uIEJ1aWxkLUNvbWFuZGEoJGRhdGEpIHsKICAkcHJv
echo ZHVjdG9zID0gR2V0LVByb2R1Y3RvcyAkZGF0YQogICR0ID0gImBuIgogICR0ICs9IENlbnRy
echo byAiR0FUTyBDQUxBVkVSQSIKICAkdCArPSBDZW50cm8gIkNPTUFOREEiCiAgJHQgKz0gTGlu
echo ZWEKICAkdCArPSBDb2wgIk1lc2EiICgkZGF0YS5tZXNhIHwgRm9yRWFjaC1PYmplY3QgeyBp
echo ZigkXyl7JF99ZWxzZXsiTi9BIn0gfSkKICAkdCArPSBDb2wgIkZlY2hhIiAoRmVjaGEpCiAg
echo JHQgKz0gTGluZWEKICBmb3JlYWNoICgkcCBpbiAkcHJvZHVjdG9zKSB7CiAgICAkbm9tYnJl
echo ID0gQ2xlYW4tVGV4dCAkcC5ub21icmUKICAgIGlmIChbc3RyaW5nXTo6SXNOdWxsT3JXaGl0
echo ZVNwYWNlKCRub21icmUpKSB7ICRub21icmUgPSAiUHJvZHVjdG8iIH0KICAgIGlmICgkbm9t
echo YnJlLkxlbmd0aCAtZ3QgMzYpIHsgJG5vbWJyZSA9ICRub21icmUuU3Vic3RyaW5nKDAsMzYp
echo IH0KICAgICRjYW50ID0gaWYgKCRwLmNhbnRpZGFkKSB7ICRwLmNhbnRpZGFkIH0gZWxzZSB7
echo IDEgfQogICAgJHQgKz0gKCJ7MH0geCB7MX1gbiIgLWYgJGNhbnQsICRub21icmUpCiAgICBp
echo ZiAoJHAubm90YXMpIHsgJHQgKz0gIk5vdGE6ICIgKyAoQ2xlYW4tVGV4dCAkcC5ub3Rhcykg
echo KyAiYG4iIH0KICAgIGlmICgkcC5sbGV2YXIgLWVxICR0cnVlKSB7ICR0ICs9ICJQQVJBIExM
echo RVZBUmBuIiB9CiAgICAkdCArPSAiYG4iCiAgfQogICR0ICs9IExpbmVhCiAgJHQgKz0gImBu
echo YG5gbiIKICByZXR1cm4gJHQKfQoKZnVuY3Rpb24gQnVpbGQtQ2llcnJlKCRkYXRhKSB7CiAg
echo JHQgPSAiYG4iCiAgJHQgKz0gQ2VudHJvICJHQVRPIENBTEFWRVJBIgogICR0ICs9IENlbnRy
echo byAiQ0lFUlJFIERFIENBSkEiCiAgJHQgKz0gTGluZWEKICAkdCArPSBDb2wgIkZlY2hhIiAo
echo RmVjaGEpCiAgaWYgKCRkYXRhLnVzdWFyaW8pIHsgJHQgKz0gQ29sICJVc3VhcmlvIiAkZGF0
echo YS51c3VhcmlvIH0KICBpZiAoJG51bGwgLW5lICRkYXRhLm1vbnRvSW5pY2lhbCkgeyAkdCAr
echo PSBDb2wgIkluaWNpYWwiIChNb25leSAkZGF0YS5tb250b0luaWNpYWwpIH0KICBpZiAoJG51
echo bGwgLW5lICRkYXRhLmVmZWN0aXZvKSB7ICR0ICs9IENvbCAiRWZlY3Rpdm8iIChNb25leSAk
echo ZGF0YS5lZmVjdGl2bykgfQogIGlmICgkbnVsbCAtbmUgJGRhdGEudGFyamV0YSkgeyAkdCAr
echo PSBDb2wgIlRhcmpldGEiIChNb25leSAkZGF0YS50YXJqZXRhKSB9CiAgaWYgKCRudWxsIC1u
echo ZSAkZGF0YS5zaW5wZSkgeyAkdCArPSBDb2wgIlNJTlBFIiAoTW9uZXkgJGRhdGEuc2lucGUp
echo IH0KICBpZiAoJG51bGwgLW5lICRkYXRhLnRvdGFsKSB7ICR0ICs9IENvbCAiVE9UQUwiIChN
echo b25leSAkZGF0YS50b3RhbCkgfQogICR0ICs9IExpbmVhCiAgJHQgKz0gImBuYG5gbiIKICBy
echo ZXR1cm4gJHQKfQoKdHJ5IHsKICBXcml0ZS1Mb2cgIkluaWNpYW5kbyBzZXJ2aWNpbyBlbiAx
echo MjcuMC4wLjE6JFBvcnQiCiAgJGxpc3RlbmVyID0gTmV3LU9iamVjdCBOZXQuSHR0cExpc3Rl
echo bmVyCiAgJGxpc3RlbmVyLlByZWZpeGVzLkFkZCgiaHR0cDovLzEyNy4wLjAuMTokUG9ydC8i
echo KQogICRsaXN0ZW5lci5TdGFydCgpCiAgV3JpdGUtTG9nICJTZXJ2aWNpbyBhY3Rpdm8iCgog
echo IHdoaWxlICgkbGlzdGVuZXIuSXNMaXN0ZW5pbmcpIHsKICAgICRjdHggPSAkbGlzdGVuZXIu
echo R2V0Q29udGV4dCgpCiAgICB0cnkgewogICAgICAkcGF0aCA9ICRjdHguUmVxdWVzdC5Vcmwu
echo QWJzb2x1dGVQYXRoLlRvTG93ZXJJbnZhcmlhbnQoKQogICAgICAkbWV0aG9kID0gJGN0eC5S
echo ZXF1ZXN0Lkh0dHBNZXRob2QuVG9VcHBlckludmFyaWFudCgpCgogICAgICAkY3R4LlJlc3Bv
echo bnNlLkhlYWRlcnMuQWRkKCJBY2Nlc3MtQ29udHJvbC1BbGxvdy1PcmlnaW4iLCAiKiIpCiAg
echo ICAgICRjdHguUmVzcG9uc2UuSGVhZGVycy5BZGQoIkFjY2Vzcy1Db250cm9sLUFsbG93LU1l
echo dGhvZHMiLCAiR0VULCBQT1NULCBPUFRJT05TIikKICAgICAgJGN0eC5SZXNwb25zZS5IZWFk
echo ZXJzLkFkZCgiQWNjZXNzLUNvbnRyb2wtQWxsb3ctSGVhZGVycyIsICJDb250ZW50LVR5cGUi
echo KQoKICAgICAgaWYgKCRtZXRob2QgLWVxICJPUFRJT05TIikgeyBTZW5kLUpzb24gJGN0eCAy
echo MDAgQHsgb2sgPSAkdHJ1ZSB9OyBjb250aW51ZSB9CiAgICAgIGlmICgkcGF0aCAtZXEgIi9o
echo ZWFsdGgiKSB7CiAgICAgICAgJGV4aXN0cyA9ICRmYWxzZQogICAgICAgIHRyeSB7ICRudWxs
echo ID0gR2V0LVByaW50ZXIgLU5hbWUgJFByaW50ZXJOYW1lIC1FcnJvckFjdGlvbiBTdG9wOyAk
echo ZXhpc3RzID0gJHRydWUgfSBjYXRjaCB7fQogICAgICAgIFNlbmQtSnNvbiAkY3R4IDIwMCBA
echo eyBvayA9ICR0cnVlOyBwcmludGVyID0gJFByaW50ZXJOYW1lOyBwcmludGVyRm91bmQgPSAk
echo ZXhpc3RzOyBtZXNzYWdlID0gIlNlcnZpY2lvIGxvY2FsIEdhdG8gQ2FsYXZlcmEgYWN0aXZv
echo IiB9CiAgICAgICAgY29udGludWUKICAgICAgfQogICAgICBpZiAoJHBhdGggLWVxICIvdGVz
echo dC1wcmludCIgLW9yICRwYXRoIC1lcSAiL3ByaW50L3Rlc3QiKSB7CiAgICAgICAgUHJpbnQt
echo VGV4dCAoQnVpbGQtVGVzdFRpY2tldCkKICAgICAgICBTZW5kLUpzb24gJGN0eCAyMDAgQHsg
echo b2sgPSAkdHJ1ZTsgbWVzc2FnZSA9ICJQcnVlYmEgZW52aWFkYSIgfQogICAgICAgIGNvbnRp
echo bnVlCiAgICAgIH0KICAgICAgaWYgKCRwYXRoIC1lcSAiL3ByaW50L2ZhY3R1cmEiKSB7CiAg
echo ICAgICAgJGRhdGEgPSBHZXQtSnNvbkJvZHkgJGN0eAogICAgICAgIFByaW50LVRleHQgKEJ1
echo aWxkLUZhY3R1cmEgJGRhdGEpCiAgICAgICAgU2VuZC1Kc29uICRjdHggMjAwIEB7IG9rID0g
echo JHRydWU7IG1lc3NhZ2UgPSAiRmFjdHVyYSBlbnZpYWRhIiB9CiAgICAgICAgY29udGludWUK
echo ICAgICAgfQogICAgICBpZiAoJHBhdGggLWVxICIvcHJpbnQvY29tYW5kYSIpIHsKICAgICAg
echo ICAkZGF0YSA9IEdldC1Kc29uQm9keSAkY3R4CiAgICAgICAgUHJpbnQtVGV4dCAoQnVpbGQt
echo Q29tYW5kYSAkZGF0YSkKICAgICAgICBTZW5kLUpzb24gJGN0eCAyMDAgQHsgb2sgPSAkdHJ1
echo ZTsgbWVzc2FnZSA9ICJDb21hbmRhIGVudmlhZGEiIH0KICAgICAgICBjb250aW51ZQogICAg
echo ICB9CiAgICAgIGlmICgkcGF0aCAtZXEgIi9wcmludC9jaWVycmUiKSB7CiAgICAgICAgJGRh
echo dGEgPSBHZXQtSnNvbkJvZHkgJGN0eAogICAgICAgIFByaW50LVRleHQgKEJ1aWxkLUNpZXJy
echo ZSAkZGF0YSkKICAgICAgICBTZW5kLUpzb24gJGN0eCAyMDAgQHsgb2sgPSAkdHJ1ZTsgbWVz
echo c2FnZSA9ICJDaWVycmUgZW52aWFkbyIgfQogICAgICAgIGNvbnRpbnVlCiAgICAgIH0KICAg
echo ICAgU2VuZC1Kc29uICRjdHggNDA0IEB7IG9rID0gJGZhbHNlOyBlcnJvciA9ICJSdXRhIG5v
echo IGVuY29udHJhZGEiIH0KICAgIH0gY2F0Y2ggewogICAgICBXcml0ZS1Mb2cgIkVycm9yIHJl
echo cXVlc3Q6ICQoJF8uRXhjZXB0aW9uLk1lc3NhZ2UpIgogICAgICB0cnkgeyBTZW5kLUpzb24g
echo JGN0eCA1MDAgQHsgb2sgPSAkZmFsc2U7IGVycm9yID0gJF8uRXhjZXB0aW9uLk1lc3NhZ2Ug
echo fSB9IGNhdGNoIHt9CiAgICB9CiAgfQp9IGNhdGNoIHsKICBXcml0ZS1Mb2cgIkVSUk9SIEZB
echo VEFMOiAkKCRfLkV4Y2VwdGlvbi5NZXNzYWdlKSIKICBTdGFydC1TbGVlcCAtU2Vjb25kcyAz
echo CiAgdGhyb3cKfQo=
) > "%SVC%\service.b64"
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$b=(Get-Content 'C:\GatoCalavera\print-service\service.b64' -Raw).Replace([Environment]::NewLine,''); [IO.File]::WriteAllBytes('C:\GatoCalavera\print-service\service.ps1',[Convert]::FromBase64String($b)); Remove-Item 'C:\GatoCalavera\print-service\service.b64' -Force"
if errorlevel 1 (echo ERROR creando service.ps1 & pause & exit /b 1)
echo [3/6] Validando impresora TERMICA...
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$p=Get-Printer -Name 'TERMICA' -ErrorAction SilentlyContinue; if($p){Write-Host 'OK: TERMICA existe'} else { $port=(Get-PrinterPort | Where-Object { $_.Name -like 'USB*' -or $_.Description -like '*POS*' } | Select-Object -First 1 -ExpandProperty Name); if(-not $port){Write-Host 'ADVERTENCIA: No se encontro TERMICA ni puerto USB de impresora. Instale la termica como TERMICA.'; exit 0}; $driver='Generic / Text Only'; if(-not(Get-PrinterDriver -Name $driver -ErrorAction SilentlyContinue)){ $inf=Join-Path $env:windir 'INF\ntprint.inf'; Start-Process rundll32.exe -ArgumentList ('printui.dll,PrintUIEntry /ia /m "'+$driver+'" /f "'+$inf+'"') -Wait }; Add-Printer -Name 'TERMICA' -DriverName $driver -PortName $port; Write-Host ('TERMICA creada en puerto '+$port) }"
echo [4/6] Registrando arranque automatico...
schtasks /Delete /TN "GatoCalaveraPrintService" /F >nul 2>&1
set "TASK_CMD=powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File C:\GatoCalavera\print-service\service.ps1"
schtasks /Create /TN "GatoCalaveraPrintService" /SC ONLOGON /TR "%TASK_CMD%" /RL HIGHEST /F >nul
if errorlevel 1 (echo ERROR registrando tarea & pause & exit /b 1)
echo [5/6] Iniciando servicio...
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Start-ScheduledTask -TaskName 'GatoCalaveraPrintService'"
timeout /t 4 /nobreak >nul
echo [6/6] Probando servicio...
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "try { $r=Invoke-RestMethod 'http://127.0.0.1:5055/health' -TimeoutSec 8; $r | ConvertTo-Json -Depth 5; exit 0 } catch { Write-Host ('ERROR: '+$_.Exception.Message); exit 1 }"
if errorlevel 1 (
  echo.
  echo No respondio el servicio. Revise logs en C:\GatoCalavera\logs\print-service.log
  echo Puede ejecutar ARRANCAR-MANUAL-V5.bat para ver el error en pantalla.
  pause
  exit /b 1
)
echo.
echo INSTALACION COMPLETA.
echo Servicio activo: http://127.0.0.1:5055/health
echo Prueba impresion: http://127.0.0.1:5055/test-print
echo.
pause
exit /b 0